[build]
builder = "DOCKERFILE"
dockerfilePath = "/worker_plan_database/Dockerfile"
watchPatterns = ["/worker_plan_database/**", "/worker_plan/**", "/database_api/**", "/llm_config.json"]
context = "."

[deploy]
restartPolicyType = "NEVER"
restartPolicyMaxRetries = 3
healthcheckInterval = 10
