[build]
builder = "DOCKERFILE"
dockerfilePath = "/worker_plan/Dockerfile"
watchPatterns = ["/worker_plan/**", "/llm_config.json"]
context = "."

[deploy]
restartPolicyType = "NEVER"
restartPolicyMaxRetries = 3
healthcheckInterval = 10
